"""Native VMEC/BOOZ conversion with public equilibria and an independent oracle."""

import hashlib
import json
from pathlib import Path

import numpy as np
import pytest
from scipy.io import netcdf_file

import gliss

booz_xform = pytest.importorskip(
    "booz_xform", reason="native VMEC conversion requires the gliss[vmec] extra"
)
pytestmark = pytest.mark.native


@pytest.fixture(scope="module")
def vmec_data(test_data):
    directory = test_data / "vmec"
    manifest = json.loads((directory / "provenance.json").read_text())
    for name, provenance in manifest["fixtures"].items():
        content = (directory / name).read_bytes()
        assert len(content) == provenance["bytes"]
        assert hashlib.sha256(content).hexdigest() == provenance["sha256"]
    return directory


def _copy_netcdf(source, destination, exclude=()):
    with netcdf_file(source, "r", mmap=False) as original:
        with netcdf_file(destination, "w", version=2) as copy:
            for name, length in original.dimensions.items():
                copy.createDimension(name, length)
            for name, value in original._attributes.items():
                setattr(copy, name, value)
            for name, variable in original.variables.items():
                if name in exclude:
                    continue
                target = copy.createVariable(name, variable.typecode(), variable.dimensions)
                for attribute, value in variable._attributes.items():
                    setattr(target, attribute, value)
                target[...] = variable.data


def test_native_boozer_matches_independent_li383_reference(native_library, vmec_data):
    transform = booz_xform.Booz_xform()
    transform.verbose = 0
    transform.read_wout(str(vmec_data / "wout_li383_lowres.nc"), True)
    transform.mboz, transform.nboz = 32, 16
    transform.compute_surfs = np.array([0, 14], dtype=np.int32)
    transform.run()
    # This upstream BOOZ_XFORM file predates the GLISS converter. Compare the
    # complete field harmonics, not a reference regenerated by GLISS.
    with netcdf_file(vmec_data / "boozmn_li383_reference.nc", "r", mmap=False) as reference:
        np.testing.assert_array_equal(transform.xm_b, reference.variables["ixm_b"].data)
        np.testing.assert_array_equal(transform.xn_b, reference.variables["ixn_b"].data)
        np.testing.assert_allclose(
            transform.bmnc_b, reference.variables["bmnc_b"].data[[0, -1]].T,
            atol=1e-12, rtol=1e-12,
        )


@pytest.mark.parametrize(
    ("name", "m", "n", "surfaces", "periods", "symmetric"),
    [("qa", 4, 3, 7, 2, True), ("lsp_asymmetric", 4, 4, 8, 3, False)],
)
def test_native_vmec_precomputed_and_native_round_trip_agree(
    native_library, vmec_data, tmp_path, name, m, n, surfaces, periods, symmetric
):
    wout = vmec_data / ("wout_qa_lowres.nc" if name == "qa" else "wout_lsp_asymmetric.nc")
    direct = gliss.convert_vmec(
        wout, tmp_path / "direct.nc", poloidal_max=m, toroidal_max=n,
        radial_surfaces=surfaces,
    )
    replay = gliss.convert_boozer(
        vmec_data / f"boozmn_{name}.nc", tmp_path / "replay.nc",
        wout_path=wout, poloidal_max=m, toroidal_max=n,
    )
    round_trip = tmp_path / "native-round-trip.nc"
    with gliss.Equilibrium(direct) as equilibrium:
        assert equilibrium.coordinate_handedness == "left-handed"
        equilibrium.write(round_trip)
    with netcdf_file(wout, "r", mmap=False) as source:
        phi = source.variables["phi"].data.copy()
    with netcdf_file(direct, "r", mmap=False) as original:
        assert original.stellarator_symmetry == (b"True" if symmetric else b"False")
        assert int(original.variables["N_FP"].data) == periods
        s = original.variables["s"].data
        np.testing.assert_allclose(
            original.variables["Phi"].data,
            -np.interp(s, np.linspace(0.0, 1.0, len(phi)), phi), atol=1e-14,
        )
        if not symmetric:
            assert np.max(np.abs(original.variables["mod_B_mns"].data)) > 1e-4
        with netcdf_file(replay, "r", mmap=False) as other:
            for field, variable in original.variables.items():
                np.testing.assert_allclose(
                    other.variables[field].data, variable.data,
                    atol=1e-13, rtol=1e-12, err_msg=field,
                )
    results = []
    for path in (direct, replay, round_trip):
        with gliss.Equilibrium(path) as equilibrium:
            with gliss.StabilityProblem(
                equilibrium, [(1, 1), (2, 1)], degree=1,
                angular_theta=32, angular_zeta=32,
            ) as problem:
                assert problem.parity_classes == ((1, 2) if symmetric else (0,))
                results.append(problem.solve())
    for result in results:
        # Both equilibria are vacuum fields: their physical ideal-MHD energy
        # is nonnegative. Direct, precomputed and native-written inputs must
        # also produce the same fixed-boundary eigenpairs.
        assert result.lowest.lowest_eigenvalue > 0.0
        assert all(item.negative_count == 0 for item in result.classes)
        np.testing.assert_allclose(
            [item.lowest_eigenvalue for item in result.classes],
            [item.lowest_eigenvalue for item in results[0].classes], rtol=1e-10,
        )


def test_native_vmec_rejects_corrupted_sign(native_library, vmec_data, tmp_path):
    source = tmp_path / "wrong-sign.nc"
    _copy_netcdf(vmec_data / "wout_qa_lowres.nc", source)
    with netcdf_file(source, "a") as file:
        file.variables["signgs"][...] = 1
    destination = tmp_path / "converted.nc"
    with pytest.raises(ValueError, match="signgs=-1"):
        gliss.convert_vmec(source, destination, poloidal_max=4, toroidal_max=3)
    assert not destination.exists()


@pytest.mark.parametrize("existing_output", [False, True])
@pytest.mark.parametrize(
    ("field", "value", "match"),
    [("nfp", 3, "nfp does not match"),
     ("ns", 51, "ns does not match its radius dimension")],
)
def test_native_boozer_rejects_mismatched_parent_grid(
    native_library, vmec_data, tmp_path, existing_output, field, value, match
):
    # Frozen QA BOOZ data have two periods and derive from a 50-point full grid.
    # Changing only the parent metadata must not yield a plausible N_FP=2 export.
    parent = tmp_path / "mismatched-parent.nc"
    _copy_netcdf(vmec_data / "wout_qa_lowres.nc", parent)
    with netcdf_file(parent, "a") as file:
        file.variables[field][...] = value
    destination = tmp_path / "converted.nc"
    preserved = b"preserve this existing output"
    if existing_output:
        destination.write_bytes(preserved)
    with pytest.raises(ValueError, match=match):
        gliss.convert_boozer(
            vmec_data / "boozmn_qa.nc", destination, wout_path=parent,
            poloidal_max=4, toroidal_max=3, overwrite=existing_output,
        )
    if existing_output:
        assert destination.read_bytes() == preserved
    else:
        assert not destination.exists()
    assert not list(tmp_path.glob(".converted.nc.*.tmp"))


@pytest.mark.parametrize("existing_output", [False, True])
def test_native_boozer_rejects_missing_asymmetric_harmonic(
    native_library, vmec_data, tmp_path, existing_output
):
    source = tmp_path / "missing-rmns.nc"
    _copy_netcdf(vmec_data / "boozmn_lsp_asymmetric.nc", source, exclude=("rmns_b",))
    destination = tmp_path / "converted.nc"
    if existing_output:
        destination.write_bytes(b"preserve this existing output")
    with pytest.raises(RuntimeError, match="cannot load BOOZ_XFORM"):
        gliss.convert_boozer(
            source, destination, wout_path=vmec_data / "wout_lsp_asymmetric.nc",
            poloidal_max=4, toroidal_max=4, overwrite=existing_output,
        )
    if existing_output:
        assert destination.read_bytes() == b"preserve this existing output"
    else:
        assert not destination.exists()
